#!/bin/bash
docker build --rm -t kakinari/centos:mysql-base .
docker run --privileged --rm --name=mysql -d kakinari/centos:mysql-base
 docker exec mysql mv /root/mysqld.service /etc/systemd/system/multi-user.target.wants
docker exec mysql systemctl enable mysqld.service
sleep 10
docker export mysql | docker import \
    -c "ENV container docker" \
    -c "ENV LANG ja_JP.UTF-8" \
    -c "ENV LANGUAGE ja_JP:ja" \
    -c "ENV LC_ALL ja_JP.UTF-8" \
    -c "ENV TZ JST-9" \
    -c "CMD /usr/sbin/init" \
    -c "WORKDIR /root" \
    -m "Mysql Server 8.0" \
    - \
    kakinari/mysql-ja:server-80
docker tag kakinari/mysql-ja:Server-8.0 kakinari/mysql-ja:latest
docker stop mysql
docker image rm -f kakinari/centos:mysql-base
docker image rm -f kakinari/centos-ja:8
docker system prune -f

