#!/bin/bash

docker build --rm -t kakinari/centos:mysql-base .
docker run --privileged --rm --name=mysql kakinari/centos:mysql-base &
sleep 10
docker export mysql | docker import \
    -c "VOLUME /sys/fs/cgroup"\
    -c "ENV container docker" \
    -c "ENV LANG ja_JP.UTF-8" \
    -c "ENV LANGUAGE ja_JP:ja" \
    -c "ENV LC_ALL ja_JP.UTF-8" \
    -c "ENV TZ JST-9" \
    -c "CMD /usr/sbin/init" \
    -c "WORKDIR /root" \
    -m "Mysql Client" \
    - \
    kakinari/centos:mysqld-80-jas
docker stop mysql
docker image rm -f kakinari/centos:mysql-base
docker image rm -f kakinari/centos:7-ja
docker system prune -f

