#!/bin/bash
docker build --rm -t devenv:devenv-ja-base .
docker run --privileged --rm -d --name=devenv devenv:devenv-ja-base
sleep 10
docker export devenv | docker import \
	-c "ENV container docker" \
	-c "ENV LANG ja_JP.UTF-8" \
	-c "ENV LANGUAGE ja_JP:ja" \
	-c "ENV LC_ALL ja_JP.UTF-8" \
	-c "ENV TZ JST-9" \
	-c "CMD [\"/usr/sbin/init\"]" \
	-c "WORKDIR /root" \
	-m "Japanese Development tools with systemd 8" \
	- kakinari/devtools-ja:8
docker stop devenv
docker image rm -f devenv:devenv-ja-base
docker image rm -f kakinari/centos-ja:8
docker system prune -f

