#!/bin/bash

docker build --rm -t centos:7-ja-base .
docker run --privileged --rm --name=cent7-ja centos:7-ja-base &
sleep 10
docker export cent7-ja | docker import \
    -c "ENV container docker" \
    -c "ENV LANG ja_JP.UTF-8" \
    -c "ENV LANGUAGE ja_JP:ja" \
    -c "ENV LC_ALL ja_JP.UTF-8" \
    -c "ENV TZ JST-9" \
    -c "CMD /usr/sbin/init" \
    -c "WORKDIR /root" \
    -m "Japanese CentOS 7 with systemd" \
    - kakinari/centos-ja:7
# docker tag kakinari/centos-ja:7 kakinari/centos-ja:latest
docker stop cent7-ja
docker image rm -f centos:7-ja-base
docker image rm -f centos:7
docker system prune -f
