#!/bin/bash
docker build --build-arg TARGET=java-11-openjdk-devel --rm -t openjdk:openjdk-ja-base .
docker run --privileged --rm -d --name=openjdk openjdk:openjdk-ja-base
sleep 10
docker export openjdk | docker import \
	-c "ENV container docker" \
	-c "ENV LANG ja_JP.UTF-8" \
	-c "ENV LANGUAGE ja_JP:ja" \
	-c "ENV LC_ALL ja_JP.UTF-8" \
	-c "ENV TZ JST-9" \
	-c "ENV JAVA_HOME /usr/lib/jvm/java-11" \
	-c "CMD [\"/usr/sbin/init\"]" \
	-c "WORKDIR /root" \
	-m "Japanese OpenJDK 11 Develop with systemd 8" \
	- kakinari/openjdk-ja:jdk-11
docker stop openjdk
docker image rm -f openjdk:openjdk-ja-base
docker image rm -f kakinari/centos-ja:8
docker system prune -f

