#!/bin/bash

docker build --rm -t tomcat-ja:base .
docker run --privileged --rm -d -p 38080:8080 --name=tomcat-ja tomcat-ja:base
sleep 10
docker exec tomcat-ja /opt/tomcat_home/bin/shutdown.sh
sleep 3
docker exec tomcat-ja rm -rf /opt/tomcat/logs/*
docker export tomcat-ja | docker import  \
	-c "CMD /usr/sbin/init" \
	-c "WORKDIR /root" \
	-c "ENV container docker" \
	-c "ENV LANG=ja_JP.UTF-8" \
	-c "ENV LANGUAGE=ja_JP:ja" \
	-c "ENV TZ=JST-9" \
	-c "ENV LC_ALL=ja_JP.UTF-8" \
	-c "ENV CATALINA_HOME=/opt/tomcat_home" \
	-c "ENV CATALINA_BASE=/opt/tomcat" \
	-c "ENV JAVA_HOME=/usr/lib/jvm/jre-1.8.0"\
	-m "Apache Tomcat 8.5 environment with ja and jre 1.8"\
	- kakinari/tomcat-ja:8.5.57
docker tag kakinari/tomcat-ja:8.5.57 kakinari/tomcat-ja:latest
docker stop tomcat-ja
docker image rm -f tomcat-ja:base
docker image rm -f kakinari/openjdk-ja:jre-1.8
docker system prune -f
