#!/bin/bash
if [[ "$1" = "" ]]
then exit;
fi

count=0
while ! nc -z -w 10 0.0.0.0 3306
do
    if [[ $count -eq 10 ]]
    then
        echo Connection timeout
        exit;
    else
        let count++
        echo $count
        sleep 3
    fi
done
TMPPWD=$(cat /var/log/mysqld.log | grep 'temporary password' | sed -e 's/^.*localhost: //')
mysqladmin --password=$TMPPWD password $1
echo "[client]" > $HOME/.my.cnf
echo "password=$1" >> $HOME/.my.cnf
chmod 600 $HOME/.my.cnf