#!/bin/bash
docker build --rm -t httpd:httpd-ja-base .
docker run --privileged --rm -d --name=httpd httpd:httpd-ja-base
sleep 10
docker exec httpd ln -s /usr/lib/systemd/system/httpd.service /etc/systemd/system/multi-user.target.wants/httpd.service 
docker exec httpd ln -s /usr/lib/systemd/system/php-fpm.service /etc/systemd/system/multi-user.target.wants/php-fpm.service
docker export httpd | docker import \
	-c "ENV container docker" \
	-c "ENV LANG ja_JP.UTF-8" \
	-c "ENV LANGUAGE ja_JP:ja" \
	-c "ENV LC_ALL ja_JP.UTF-8" \
	-c "ENV TZ JST-9" \
	-c "ENV JAVA_HOME /usr/lib/jvm/jre-11" \
	-c "CMD [\"/usr/sbin/init\"]" \
	-c "WORKDIR /var/www/html" \
	-m "Japanese Apache Httpd with systemd 8" \
	- kakinari/httpd-ja:24-php
docker stop httpd
docker image rm -f httpd:httpd-ja-base
docker image rm -f kakinari/centos-ja:8
docker system prune -f

