#!/bin/bash

docker build --rm -t centos:ja-base .
docker run --privileged --rm --name=cent-ja centos:ja-base &
sleep 10
docker export cent-ja | docker import \
    -c "ENV container docker" \
    -c "ENV LANG ja_JP.UTF-8" \
    -c "ENV LANGUAGE ja_JP:ja" \
    -c "ENV LC_ALL ja_JP.UTF-8" \
    -c "ENV TZ JST-9" \
    -c "CMD [ \"/usr/sbin/init\" ] " \
    -c "WORKDIR /root" \
    -m "Japanese CentOS 8 with systemd" \
    - kakinari/centos-ja:8
docker stop cent-ja
docker image rm -f centos:ja-base
docker image rm -f centos:8
docker system prune -f
